# Generated by Django 3.2.4 on 2021-06-28 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userlist', '0004_auto_20210624_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='create_at',
            field=models.DateTimeField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='update_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
